name: Workflow - build vb-with-ext and push to cachix
on:
  workflow_dispatch:

jobs:
  Build-and-Cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - run: cd ./local/ && nix build .#vb-with-ext -vL
      - run: readlink local/result | nix run nixpkgs#cachix
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
